run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - goconst
    - unconvert
    - dupl
    - bodyclose
    - noctx
    - rowserrcheck
    - sqlclosecheck
  disable:
    - gocyclo
    - gosec
    - exportloopref

linters-settings:
  gocyclo:
    min-complexity: 15
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - goconst
    - path: internal/handler/rpc/
      linters:
        - dupl
  max-issues-per-linter: 0
  max-same-issues: 0
